Allow EnergySystems Hizard to modify PV parameters and fix highlighting issues
architecture-building-systems/hive pull request #666
Opened 2021-11-07 16:53 UTC by philipschulz

## Issues

Closes #663

2021-11-08 17:54 UTC, christophwaibel commented
it works! But there is one cosmetic bug. When clicking first into either one of the textboxes for `Module Efficiency`, `Specific Capital Cost`, or `Specific Embodied Emissions` and then clicking again into one of those textboxes, the value in the textbox for `Area` disappears. It re-appears upon re-opening the hizard:

![image](https://user-images.githubusercontent.com/21927657/140792606-4a379a68-eedb-4751-8da8-48827eefbbd8.png)

![image](https://user-images.githubusercontent.com/21927657/140793183-76e52f99-e140-401d-8e42-c0bf42d0853d.png)

2021-11-08 17:56 UTC, christophwaibel requested changes
one cosmetic bug related to value for `Area` disappearing

2021-11-08 17:56 UTC, christophwaibel commented on src/Hive.IO/Hive.IO/Forms/Controls/SurfaceTechnologyProperties.cs
> +
not sure if the problem comes from here, but see [this comment](https://github.com/architecture-building-systems/hive/pull/666#issuecomment-963412851)

2021-11-10 12:28 UTC, christophwaibel commented
on my desktop, the hizard is narrower now. It won't properly display the "Module Type" drop down list. I actually like it smaller like that, but can you fix the displaying issue of the Module Type list?

![image](https://user-images.githubusercontent.com/21927657/141112211-2cd2a219-2898-43de-9455-79e44b655009.png)

It seems to auto-size-down to the width of the Source-Conversion-EndUse grid:

![image](https://user-images.githubusercontent.com/21927657/141112320-ddb2a1a8-d362-4176-84e5-566e729e5123.png)

2021-11-10 12:30 UTC, christophwaibel commented
Also, now, none of the parameters are showing up anymore. Hence, we can't change efficiency, etc., which was the original purpose of this PR ;-D  
See same screenshot above.

2021-11-11 12:21 UTC, philipschulz commented
![image](https://user-images.githubusercontent.com/16674735/141297014-f3d10a64-6b72-4d49-9941-0e7d64574c61.png)
Uh, I'm not sure whats going on here, it look like this for me...

2021-11-11 12:47 UTC, christophwaibel commented
hmm rebuilt on my home desktop and now also looks ok. Will merge for now and try on different computers

2021-11-11 12:47 UTC, merged