Migration of all EnergySystems and Solar/SolarTech Components to C#
architecture-building-systems/hive pull request #722
Opened 2022-03-24 11:43 UTC by philipschulz

# Migration of all EnergySystems and Solar/SolarTech Components to C#

## Issues

Closes #697 

## Description

- All Components from the EnergySystems and Solar groups implemented in C#. Currently, both versions are available concurrently. To remove the python-versions, edit build and .nsi scripts so the python versions do not get built and installed.
- Behaviour of SumOverTimePeriod is slightly different, the example in simple_pv.gh shows both versions and how the values have to be extracted slightly differently.

## Checklist

- [ ] Remove debugging artifacts (if needed)
- [ ] Rebuild the Setup_Hive.exe
- [ ] Update Hive Wiki (if needed)
- [ ] Update InformationalVersion attribute in Hive.IO/Properties/AssemblyInfo.cs (if it's a new release) 
- [ ] Update most important Grasshopper template(s); as of now [/GrasshopperExamples/LectureExercises/EaCS3_E04_Hive_Template.gh](https://github.com/architecture-building-systems/hive/blob/master/GrasshopperExamples/LectureExercises/EaCS3_E04_Hive_Template.gh)

2022-03-28 18:46 UTC, christophwaibel commented
@philipschulz as per discussion in our sprint today, can you clean up `simple_pv.gh` and notify me once done? Then, I'll review this PR (and merge it)

2022-03-31 13:55 UTC, philipschulz commented
@christophwaibel cleaned up simple_pv.gh

2022-04-01 16:56 UTC, christophwaibel requested changes

2022-04-06 20:31 UTC, christophwaibel approved these changes

2022-04-06 20:39 UTC, christophwaibel commented
thanks @philipschulz , works fine now! merging

2022-04-06 20:39 UTC, merged